import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div
          style={{
            backgroundColor: "#EBE8DD",
            color: "#274E3F",
          }}
        >
          {children}
        </div>
      </body>
    </html>
  )
}
